server:
  port: 8088

spring:
  application:
    name: spring-cloud-consumer

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.43.211:8848