server:
  port: 8077

spring:
  profiles:
    active: prod
  application:
    name: user-provider

  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 192.168.43.211:8848

log:
  path: ./logs